# Generated by Django 5.0.6 on 2025-12-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_ticket_alter_job_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ship_to_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ship_to_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ship_to_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ship_to_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ship_to_zip',
        ),
        migrations.CreateModel(
            name='CustomerShipToAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Label like 'Warehouse 1', 'Main Office', etc.", max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_addresses', to='jobs.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='customershiptoaddress',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_customer_ship_to_name'),
        ),
    ]
