# Generated by Django 5.0.6 on 2025-12-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_price_setting',
            field=models.CharField(blank=True, choices=[('list', 'List'), ('jobber', 'Jobber')], help_text='Default price setting for this customer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_terms',
            field=models.CharField(blank=True, choices=[('net_30', 'Net 30'), ('1pct_10', '1% 10'), ('other', 'Other')], help_text='Default payment terms for this customer', max_length=20, null=True),
        ),
    ]
