# Generated by Django 5.0.6 on 2025-12-03 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_customer_default_price_setting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobemployee',
            name='calculated_total_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked', max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('quote', 'Quote'), ('wo', 'WO'), ('invoice', 'Invoice')], max_length=20, null=True),
        ),
    ]
