# Generated by Django 5.0.6 on 2025-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_employee_options_remove_employee_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbuildlist',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobbuildlist',
            name='time_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked', max_digits=10),
        ),
    ]
