# Generated by Django 5.0.6 on 2025-12-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobbuildlist_selected_jobbuildlist_time_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtime',
            name='job_build_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='jobs.jobbuildlist'),
        ),
    ]
