# Generated by Django 5.0.6 on 2025-12-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobtime_job_build_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='parent_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='jobs.jobnotification'),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='type',
            field=models.CharField(blank=True, choices=[('step_completed', 'Step Completed'), ('po_missing_on_close', 'PO Missing on Close'), ('generic', 'Generic'), ('team_message', 'Team Message'), ('reply', 'Reply')], max_length=50, null=True),
        ),
    ]
