# Generated by Django 5.0.6 on 2025-12-04 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_employee_user_jobnotification_parent_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtime',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='jobemployee',
            name='employee',
        ),
        migrations.AddField(
            model_name='jobemployee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
