# Generated by Django 5.0.6 on 2025-12-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_add_engine_identifier'),
        ('jobs', '0012_alter_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.part'),
        ),
    ]

