# Generated by Django 5.0.6 on 2025-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_purchaseorderitem_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcomponent',
            name='main_bearing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcomponent',
            name='main_bearing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcomponent',
            name='piston_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
