# Generated by Django 5.0.2 on 2025-08-20 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('original_data', models.JSONField()),
                ('normalized_machine_data', models.JSONField(blank=True, default=dict)),
                ('normalized_engine_data', models.JSONField(blank=True, default=dict)),
                ('normalized_part_data', models.JSONField(blank=True, default=dict)),
                ('machine_created', models.BooleanField(default=False)),
                ('machine_updated', models.BooleanField(default=False)),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('engine_created', models.BooleanField(default=False)),
                ('engine_updated', models.BooleanField(default=False)),
                ('engine_id', models.IntegerField(blank=True, null=True)),
                ('part_created', models.BooleanField(default=False)),
                ('part_updated', models.BooleanField(default=False)),
                ('part_id', models.IntegerField(blank=True, null=True)),
                ('machine_engine_created', models.BooleanField(default=False)),
                ('engine_part_created', models.BooleanField(default=False)),
                ('part_vendor_created', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
                'indexes': [models.Index(fields=['batch', 'row_number'], name='imports_imp_batch_i_84671a_idx'), models.Index(fields=['has_errors'], name='imports_imp_has_err_cb0d97_idx')],
                'unique_together': {('batch', 'row_number')},
            },
        ),
    ]
