# Generated by Django 5.0.2 on 2025-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
