# Generated by Django 5.0.2 on 2025-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_add_started_finished_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='started_at',
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='part_attribute_mappings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
