# Generated by Django 5.0.6 on 2025-09-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_add_part_attribute_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='celery_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking async processing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
