# Generated by Django 5.0.6 on 2025-09-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_add_celery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='engine_vendor_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_vendor_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='vendor_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='vendor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='vendor_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='vendor_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
