# Generated by Django 5.0.6 on 2025-09-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_add_vendor_mapping_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='sg_vendor_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='sg_vendor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='sg_vendor_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='vendor_alias_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='create_missing_sg_vendors',
            field=models.BooleanField(default=False),
        ),
    ]
