# Generated by Django 5.0.6 on 2025-09-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_add_sg_vendor_import_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importrow',
            name='sg_vendor_created',
        ),
        migrations.RemoveField(
            model_name='importrow',
            name='sg_vendor_id',
        ),
        migrations.RemoveField(
            model_name='importrow',
            name='sg_vendor_matched',
        ),
        migrations.RemoveField(
            model_name='importrow',
            name='vendor_alias_created',
        ),
        migrations.RemoveField(
            model_name='savedimportmapping',
            name='create_missing_sg_vendors',
        ),
    ]
