# Generated by Django 5.0.6 on 2025-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_remove_importrow_sg_vendor_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='engine_duplicate_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='engine_duplicate_updated',
            field=models.BooleanField(default=False),
        ),
    ]
