# Generated by Django 5.0.6 on 2025-11-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_add_engine_duplicate_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='machine_part_created',
            field=models.BooleanField(default=False),
        ),
    ]
