# Generated by Django 5.0.6 on 2025-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0010_add_machine_part_created_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Set to True to request cancellation of processing'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20),
        ),
    ]
