# Generated by Django 5.0.6 on 2025-11-13 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0011_importbatch_cancel_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reverted', 'Reverted')], default='uploaded', max_length=20),
        ),
    ]
