# Generated by Django 5.0.6 on 2025-11-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0012_importbatch_reverted_at_importbatch_reverted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='buildlist_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='buildlist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='buildlist_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='buildlistitem_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='buildlistitem_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='kit_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='kit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='kit_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='kititem_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='kititem_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_buildlist_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_buildlistitem_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_kit_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_kititem_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='part_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='buildlist_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='buildlistitem_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='kit_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedimportmapping',
            name='kititem_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
