# Generated by Django 5.0.2 on 2025-08-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_machinepart_machine_parts_part_machines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='compatibles',
            field=models.ManyToManyField(blank=True, related_name='compatible_with', to='inventory.engine'),
        ),
        migrations.AddField(
            model_name='engine',
            name='interchanges',
            field=models.ManyToManyField(blank=True, related_name='interchanged_with', to='inventory.engine'),
        ),
        migrations.CreateModel(
            name='EngineSupercession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('from_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superseded_by_links', to='inventory.engine')),
                ('to_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersedes_links', to='inventory.engine')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enginesupercession',
            constraint=models.UniqueConstraint(fields=('from_engine', 'to_engine'), name='unique_supercession'),
        ),
    ]
