# Generated by Django 5.0.2 on 2025-08-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_enginesupercession_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=140)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('dec', 'Decimal'), ('bool', 'Boolean'), ('date', 'Date'), ('choice', 'Choice')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PartAttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='PartAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_int', models.BigIntegerField(blank=True, null=True)),
                ('value_dec', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.partcategory'),
        ),
        migrations.AddField(
            model_name='partattributechoice',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='inventory.partattribute'),
        ),
        migrations.AddField(
            model_name='partattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.partattribute'),
        ),
        migrations.AddField(
            model_name='partattributevalue',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partattributechoice'),
        ),
        migrations.AddField(
            model_name='partattributevalue',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='inventory.part'),
        ),
        migrations.AlterUniqueTogether(
            name='partattribute',
            unique_together={('category', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='partattributechoice',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='partattributevalue',
            unique_together={('part', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='partattributevalue',
            index=models.Index(fields=['attribute', 'value_text'], name='inventory_p_attribu_871359_idx'),
        ),
        migrations.AddIndex(
            model_name='partattributevalue',
            index=models.Index(fields=['attribute', 'value_int'], name='inventory_p_attribu_d2a285_idx'),
        ),
        migrations.AddIndex(
            model_name='partattributevalue',
            index=models.Index(fields=['attribute', 'value_dec'], name='inventory_p_attribu_7de7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='partattributevalue',
            index=models.Index(fields=['attribute', 'value_bool'], name='inventory_p_attribu_0eaf22_idx'),
        ),
        migrations.AddIndex(
            model_name='partattributevalue',
            index=models.Index(fields=['attribute', 'value_date'], name='inventory_p_attribu_e61ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='partattributevalue',
            index=models.Index(fields=['attribute', 'choice'], name='inventory_p_attribu_173aa2_idx'),
        ),
    ]
