# Generated by Django 5.0.2 on 2025-08-22 18:21

import django.db.models.deletion
from django.db import migrations, models


def copy_preferred_vendor_data(apps, schema_editor):
    """Copy data from preferred_vendor to primary_vendor field before removing the old field."""
    Part = apps.get_model('inventory', 'Part')
    
    # Get all parts that have a preferred_vendor
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, preferred_vendor_id 
            FROM inventory_part 
            WHERE preferred_vendor_id IS NOT NULL
        """)
        results = cursor.fetchall()
    
    # Update each part with the primary_vendor
    for part_id, vendor_id in results:
        if vendor_id:
            Part.objects.filter(id=part_id).update(primary_vendor_id=vendor_id)


def reverse_copy_preferred_vendor_data(apps, schema_editor):
    """Reverse the data copy operation."""
    Part = apps.get_model('inventory', 'Part')
    
    # Copy data back from primary_vendor to preferred_vendor
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, primary_vendor_id 
            FROM inventory_part 
            WHERE primary_vendor_id IS NOT NULL
        """)
        results = cursor.fetchall()
    
    # Update each part with the preferred_vendor
    for part_id, vendor_id in results:
        if vendor_id:
            Part.objects.filter(id=part_id).update(preferred_vendor_id=vendor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_convert_part_category_to_foreign_key'),
    ]

    operations = [
        # First add the new field
        migrations.AddField(
            model_name='part',
            name='primary_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_parts', to='inventory.vendor'),
        ),
        # Copy data from old field to new field
        migrations.RunPython(
            copy_preferred_vendor_data,
            reverse_copy_preferred_vendor_data,
        ),
        # Remove the old field
        migrations.RemoveField(
            model_name='part',
            name='preferred_vendor',
        ),
        # Add the notes field to PartVendor
        migrations.AddField(
            model_name='partvendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        # Update the cost field precision
        migrations.AlterField(
            model_name='partvendor',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
