# Generated by Django 5.0.2 on 2025-08-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_preferred_vendor_to_primary_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_lists', to='inventory.engine')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='inventory.buildlist')),
            ],
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.kit')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.vendor')),
            ],
            options={
                'unique_together': {('kit', 'part', 'vendor')},
            },
        ),
    ]
