# Generated by Django 5.0.2 on 2025-08-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_update_sg_engine_identifiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partvendor',
            options={'ordering': ['vendor__name']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='partvendor',
            name='unique_part_vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='partvendor',
            name='lead_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partvendor',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_links', to='inventory.part'),
        ),
        migrations.AlterField(
            model_name='partvendor',
            name='stock_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_links', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='partvendor',
            name='vendor_sku',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='partvendor',
            unique_together={('part', 'vendor')},
        ),
    ]
