# Generated by Django 5.0.6 on 2025-09-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_partvendor_options_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='casting_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Casting # Comments'),
        ),
        migrations.AddField(
            model_name='engine',
            name='common_rail',
            field=models.BooleanField(default=False, verbose_name='Common Rail'),
        ),
        migrations.AddField(
            model_name='engine',
            name='di',
            field=models.BooleanField(default=False, verbose_name='DI (Direct Injection)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='five_valve',
            field=models.BooleanField(default=False, verbose_name='5V (5 Valve)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='four_valve',
            field=models.BooleanField(default=False, verbose_name='4V (4 Valve)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='idi',
            field=models.BooleanField(default=False, verbose_name='IDI (Indirect Injection)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='S/N'),
        ),
        migrations.AddField(
            model_name='engine',
            name='two_valve',
            field=models.BooleanField(default=False, verbose_name='2V (2 Valve)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='compatibles',
            field=models.ManyToManyField(blank=True, to='inventory.engine'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='interchanges',
            field=models.ManyToManyField(blank=True, to='inventory.engine'),
        ),
    ]
