# Generated by Django 5.0.6 on 2025-09-17 00:12

from django.db import migrations


def migrate_vendor_contacts(apps, schema_editor):
    """Migrate existing vendor contact data to VendorContact model."""
    Vendor = apps.get_model('inventory', 'Vendor')
    VendorContact = apps.get_model('inventory', 'VendorContact')
    
    for vendor in Vendor.objects.all():
        # Only create a contact if the vendor has contact information
        if vendor.contact_name or vendor.email or vendor.phone:
            VendorContact.objects.create(
                vendor=vendor,
                full_name=vendor.contact_name or '',
                email=vendor.email or '',
                phone=vendor.phone or '',
                title='',  # No title field in original model
                notes=''   # No notes field in original model
            )


def reverse_migrate_vendor_contacts(apps, schema_editor):
    """Reverse migration - this is not easily reversible, so we'll just pass."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_vendor_contact'),
    ]

    operations = [
        migrations.RunPython(migrate_vendor_contacts, reverse_migrate_vendor_contacts),
    ]
