# Generated by Django 5.0.6 on 2025-09-17 23:30

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_vendor_constraint_and_engine_vendor_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, help_text="Source of this alias (e.g., 'import', 'manual', 'migration')", max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SGVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='sgvendor_name_lower_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sgvendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_sgvendor_lower_name', violation_error_message='SG Vendor with this name already exists (case-insensitive)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sg_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='inventory.sgvendor'),
        ),
        migrations.AddField(
            model_name='vendoralias',
            name='sg_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.sgvendor'),
        ),
        migrations.AddIndex(
            model_name='vendoralias',
            index=models.Index(django.db.models.functions.text.Lower('alias'), name='vendoralias_alias_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendoralias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('alias'), name='uq_vendoralias_lower_alias', violation_error_message='Vendor alias with this name already exists (case-insensitive)'),
        ),
    ]
