# Generated by Django 5.0.6 on 2025-09-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_sg_vendor_system'),
    ]

    operations = [
    ]
