# Generated by Django 5.0.6 on 2025-09-18 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_migrate_existing_vendors_to_sg_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoralias',
            name='sg_vendor',
        ),
        migrations.RenameIndex(
            model_name='sgvendor',
            new_name='idx_sgvendor_lower_name',
            old_name='sgvendor_name_lower_idx',
        ),
        migrations.AddField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.vendor'),
        ),
        migrations.DeleteModel(
            name='VendorAlias',
        ),
    ]
