# Generated by Django 5.0.6 on 2025-09-18 05:01

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_sgvendor_and_vendor_fks'),
    ]

    operations = [
        # Enable pg_trgm extension for trigram indexes
        TrigramExtension(),
        
        # Add trigram indexes for better search performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS engine_make_trgm_idx ON inventory_engine USING gin (engine_make gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS engine_make_trgm_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS engine_model_trgm_idx ON inventory_engine USING gin (engine_model gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS engine_model_trgm_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS engine_identifier_trgm_idx ON inventory_engine USING gin (sg_engine_identifier gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS engine_identifier_trgm_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS engine_cpl_trgm_idx ON inventory_engine USING gin (cpl_number gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS engine_cpl_trgm_idx;"
        ),
    ]
