# Generated by Django 5.0.6 on 2025-09-18 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20250917_2301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in pounds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partvendor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='partvendor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partvendor',
            name='vendor_part_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='partvendor',
            index=models.Index(fields=['part', 'vendor'], name='inventory_p_part_id_16e8a6_idx'),
        ),
    ]
