# Generated by Django 5.0.6 on 2025-11-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_buildlist_engines(apps, schema_editor):
    """Migrate existing BuildList.engine ForeignKey to BuildList.engines ManyToMany."""
    BuildList = apps.get_model('inventory', 'BuildList')
    for build_list in BuildList.objects.all():
        if hasattr(build_list, 'engine_id') and build_list.engine_id:
            build_list.engines.add(build_list.engine_id)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_part_weight_partvendor_price_partvendor_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hour_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='buildlist',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='buildlist',
            name='unique_buildlist_per_engine',
        ),
        migrations.AddField(
            model_name='buildlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildlist',
            name='engines',
            field=models.ManyToManyField(blank=True, related_name='build_lists', to='inventory.engine'),
        ),
        migrations.RunPython(migrate_buildlist_engines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='buildlist',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='build_list',
        ),
        migrations.AddField(
            model_name='buildlistitem',
            name='build_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.buildlist'),
        ),
    ]
