# Generated by Django 5.0.6 on 2025-11-12 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_buildlistitem_alter_buildlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='kititem',
            options={'ordering': ['part__part_number']},
        ),
        migrations.RemoveField(
            model_name='kit',
            name='cost_total',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='margin_pct',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='sale_price',
        ),
        migrations.AlterUniqueTogether(
            name='kititem',
            unique_together={('kit', 'part')},
        ),
        migrations.AddField(
            model_name='kit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kit',
            name='engines',
            field=models.ManyToManyField(blank=True, related_name='kits', to='inventory.engine'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kititem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='kititem',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='kititem',
            name='vendor',
        ),
    ]
