# Generated by Django 5.0.6 on 2025-11-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_kit_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_number', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='inventory.engine')),
            ],
            options={
                'ordering': ['casting_number'],
            },
        ),
    ]
