# Generated by Django 5.0.6 on 2025-11-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_casting_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='casting_comments',
        ),
    ]
