# Generated by Django 5.0.6 on 2025-11-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_casting_comments_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machine',
            name='unique_machine_key',
        ),
        migrations.RemoveConstraint(
            model_name='part',
            name='unique_part_number_name',
        ),
        migrations.RemoveConstraint(
            model_name='sgengine',
            name='unique_sg_engine_make_model',
        ),
        migrations.RemoveConstraint(
            model_name='sgvendor',
            name='uq_sgvendor_lower_name',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='uq_vendor_lower_name',
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='market_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgengine',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgengine',
            name='sg_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgengine',
            name='sg_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sgvendor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
