# Generated by Django 5.0.6 on 2025-11-13 21:14

from django.db import migrations


def create_unknown_defaults(apps, schema_editor):
    """Create Unknown default records for FK fields."""
    SGEngine = apps.get_model('inventory', 'SGEngine')
    Vendor = apps.get_model('inventory', 'Vendor')
    SGVendor = apps.get_model('inventory', 'SGVendor')
    PartCategory = apps.get_model('inventory', 'PartCategory')
    
    # Create Unknown SGEngine if it doesn't exist
    SGEngine.objects.get_or_create(
        identifier='UNKNOWN_DEFAULT',
        defaults={
            'sg_make': 'Unknown',
            'sg_model': 'Unknown',
            'notes': 'Default record for imports without engine information'
        }
    )
    
    # Create Unknown SGVendor if it doesn't exist
    SGVendor.objects.get_or_create(
        name='Unknown',
        defaults={
            'notes': 'Default record for imports without vendor information'
        }
    )
    
    # Create Unknown Vendor if it doesn't exist
    Vendor.objects.get_or_create(
        name='Unknown',
        defaults={
            'notes': 'Default record for imports without vendor information'
        }
    )
    
    # Create Uncategorized PartCategory if it doesn't exist
    PartCategory.objects.get_or_create(
        name='Uncategorized',
        defaults={
            'slug': 'uncategorized'
        }
    )


def reverse_create_unknown_defaults(apps, schema_editor):
    """Remove Unknown default records."""
    SGEngine = apps.get_model('inventory', 'SGEngine')
    Vendor = apps.get_model('inventory', 'Vendor')
    SGVendor = apps.get_model('inventory', 'SGVendor')
    PartCategory = apps.get_model('inventory', 'PartCategory')
    
    # Delete Unknown records (only if they exist and are truly defaults)
    SGEngine.objects.filter(identifier='UNKNOWN_DEFAULT').delete()
    SGVendor.objects.filter(name='Unknown').delete()
    Vendor.objects.filter(name='Unknown').delete()
    PartCategory.objects.filter(slug='uncategorized').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_machine_unique_machine_key_and_more'),
    ]

    operations = [
        migrations.RunPython(create_unknown_defaults, reverse_create_unknown_defaults),
    ]
