# Generated by Django 5.0.6 on 2025-11-26 00:14

from django.db import migrations, models


def migrate_engine_characteristics_forward(apps, schema_editor):
    """Convert boolean fields to text fields."""
    Engine = apps.get_model('inventory', 'Engine')
    
    for engine in Engine.objects.all():
        # Migrate injection type
        if engine.di:
            engine.injection_type = 'DI'
        elif engine.idi:
            engine.injection_type = 'IDI'
        
        # Migrate valve configuration
        valve_configs = []
        if engine.two_valve:
            valve_configs.append('2V')
        if engine.four_valve:
            valve_configs.append('4V')
        if engine.five_valve:
            valve_configs.append('5V')
        if valve_configs:
            engine.valve_config = ', '.join(valve_configs)
        
        # Migrate fuel system type
        if engine.common_rail:
            engine.fuel_system_type = 'Common Rail'
        
        engine.save(update_fields=['injection_type', 'valve_config', 'fuel_system_type'])


def migrate_engine_characteristics_backward(apps, schema_editor):
    """Convert text fields back to boolean fields."""
    Engine = apps.get_model('inventory', 'Engine')
    
    for engine in Engine.objects.all():
        # Migrate injection type back to booleans
        if engine.injection_type:
            injection_lower = engine.injection_type.lower()
            if 'di' in injection_lower and 'idi' not in injection_lower:
                engine.di = True
            elif 'idi' in injection_lower:
                engine.idi = True
        
        # Migrate valve configuration back to booleans
        if engine.valve_config:
            valve_lower = engine.valve_config.lower()
            if '2v' in valve_lower or '2 valve' in valve_lower:
                engine.two_valve = True
            if '4v' in valve_lower or '4 valve' in valve_lower:
                engine.four_valve = True
            if '5v' in valve_lower or '5 valve' in valve_lower:
                engine.five_valve = True
        
        # Migrate fuel system type back to boolean
        if engine.fuel_system_type and 'common rail' in engine.fuel_system_type.lower():
            engine.common_rail = True
        
        engine.save(update_fields=['di', 'idi', 'two_valve', 'four_valve', 'five_valve', 'common_rail'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_create_unknown_defaults'),
    ]

    operations = [
        # Step 1: Add new fields
        migrations.AddField(
            model_name='engine',
            name='fuel_system_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fuel System Type'),
        ),
        migrations.AddField(
            model_name='engine',
            name='injection_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Injection Type'),
        ),
        migrations.AddField(
            model_name='engine',
            name='valve_config',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valve Configuration'),
        ),
        # Step 2: Migrate data from old fields to new fields
        migrations.RunPython(
            migrate_engine_characteristics_forward,
            migrate_engine_characteristics_backward,
        ),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name='engine',
            name='common_rail',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='di',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='five_valve',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='four_valve',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='idi',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='two_valve',
        ),
    ]
