# Generated by Django 5.0.6 on 2025-11-26 00:27

from django.db import migrations


def auto_set_primary_vendors(apps, schema_editor):
    """Set primary_vendor for all parts with exactly one vendor."""
    Part = apps.get_model('inventory', 'Part')
    PartVendor = apps.get_model('inventory', 'PartVendor')
    
    updated_count = 0
    cleared_count = 0
    
    for part in Part.objects.all():
        vendor_links = PartVendor.objects.filter(part=part)
        vendor_count = vendor_links.count()
        
        if vendor_count == 1:
            # Set primary vendor to the single vendor
            single_vendor = vendor_links.first().vendor
            if part.primary_vendor != single_vendor:
                part.primary_vendor = single_vendor
                part.save(update_fields=['primary_vendor'])
                updated_count += 1
        elif vendor_count == 0:
            # Clear primary vendor if no vendors exist
            if part.primary_vendor is not None:
                part.primary_vendor = None
                part.save(update_fields=['primary_vendor'])
                cleared_count += 1
    
    print(f"Auto-set primary vendor for {updated_count} parts with single vendor")
    print(f"Cleared primary vendor for {cleared_count} parts with no vendors")


def reverse_auto_set_primary_vendors(apps, schema_editor):
    """Reverse migration - no action needed as this is just setting convenience data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_refactor_engine_characteristics'),
    ]

    operations = [
        migrations.RunPython(
            auto_set_primary_vendors,
            reverse_auto_set_primary_vendors,
        ),
    ]
