# Generated by Django 5.0.6 on 2025-11-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_set_primary_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifier'),
        ),
    ]
