# Generated by Django 5.0.6 on 2025-12-04 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_state', models.CharField(blank=True, max_length=50, null=True)),
                ('company_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('default_price_setting', models.CharField(blank=True, choices=[('list', 'List'), ('jobber', 'Jobber')], default='list', max_length=20, null=True)),
                ('default_terms', models.CharField(blank=True, choices=[('net_30', 'Net 30'), ('1pct_10', '1% 10'), ('other', 'Other')], default='net_30', max_length=20, null=True)),
                ('date_format', models.CharField(blank=True, choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20, null=True)),
                ('items_per_page', models.PositiveIntegerField(default=25, help_text='Default number of items to show per page in lists')),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='Enable email notifications for job updates')),
                ('notification_email_from', models.EmailField(blank=True, help_text='From address for system emails', max_length=254, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('can_view_jobs', models.BooleanField(default=True)),
                ('can_edit_jobs', models.BooleanField(default=False)),
                ('can_delete_jobs', models.BooleanField(default=False)),
                ('can_manage_job_options', models.BooleanField(default=False)),
                ('can_view_inventory', models.BooleanField(default=True)),
                ('can_edit_inventory', models.BooleanField(default=False)),
                ('can_delete_inventory', models.BooleanField(default=False)),
                ('can_view_imports', models.BooleanField(default=False)),
                ('can_create_imports', models.BooleanField(default=False)),
                ('can_revert_imports', models.BooleanField(default=False)),
                ('can_view_employees', models.BooleanField(default=True)),
                ('can_edit_employees', models.BooleanField(default=False)),
                ('can_delete_employees', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_manage_system_config', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_export_reports', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='settings_app.userrole')),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
