# Generated by Django 5.0.6 on 2025-12-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_price_setting',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_terms',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='items_per_page',
        ),
    ]
